In [3]:
import torch
import numpy as np

In [17]:
A = torch.from_numpy(np.array([[2., 3.], [1., 0.]]))
A.requires_grad = True

B = torch.from_numpy(np.array([[1., 2.], [3., 4.]]))
B.requires_grad = True

C = torch.matmul(A, B)
print(C)

d = torch.from_numpy(np.array([[3.], [2.]]))
d.requires_grad = True

print(d)

# Broadcasting de d
E = C + d

print(E)

J = torch.sum(E)

print(J)

tensor([[11., 16.],
        [ 1.,  2.]], dtype=torch.float64, grad_fn=<MmBackward0>)
tensor([[3.],
        [2.]], dtype=torch.float64, requires_grad=True)
tensor([[14., 19.],
        [ 3.,  4.]], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(40., dtype=torch.float64, grad_fn=<SumBackward0>)


In [18]:
J.backward()

In [19]:
d.grad

tensor([[2.],
        [2.]], dtype=torch.float64)

In [20]:
A.grad

tensor([[3., 7.],
        [3., 7.]], dtype=torch.float64)

In [21]:
B.grad

tensor([[3., 3.],
        [3., 3.]], dtype=torch.float64)